general {
  # Without this the screen wont turn on on its own after resume.
  after_sleep_cmd = hyprctl dispatch dpms on
}

# 5m, turn off/on screen
listener {
  timeout = 300
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}

# 8m, suspend
listener {
  timeout = 480
  on-timeout = systemctl suspend
}
# 2h, force suspend
listener {
  timeout = 7200
  on-timeout = systemctl suspend
  ignore_inhibit = true
}
