# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
let
  ssd-options = [
    "noatime"
    "nodiratime"
  ];
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../modules/system/usb-wakeup.nix
  ];
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [];
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  hardware.amdgpu = {
    initrd.enable = true;
  };
  # Disable everything but the keyboard from waking up the computer.
  # This is due to mouse sending wake up signals randomly.
  hardware.usb.wakeup = {
    enable = true;
    mode = "whitelist";
    devices.keyboard = {
      vendor = "413c";
      product = "2003";
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-label/NixOS";
    fsType = "ext4";
    options = ssd-options;
  };
  # Allow kernels/initrd to be kept on the main partition
  # Only works on grub, allows keeping far more generations
  # As these files can fill up the entire boot drive sometimes.
  #boot.loader.efi.efiSysMountPoint = "/boot";
  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/Home";
    fsType = "ext4";
    options = ssd-options;
  };

  fileSystems."/run/media/bikku/Data-HDD" = {
    device = "/dev/disk/by-label/Data-HDD";
    fsType = "ext4";
  };

  fileSystems."/run/media/bikku/Data-SSD" = {
    device = "/dev/disk/by-label/Data-SSD";
    fsType = "ext4";
    options = ssd-options;
  };
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      # RedHat recommends 0.5/1.5 * RAM depending on whether hibernation is on or off
      size = builtins.ceil (0.5 * 16 * 1024);
      randomEncryption.enable = true;
    }
  ];
  zramSwap.enable = true;
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  hardware.enableAllFirmware = true;
  # Why the hell was this off by default. Am I missing something?
  # And why knowing this is off by default had me going through a trail of options.
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
